{*
 * @version    $Id: template.phtml 2 2009-07-13 20:58:52Z david@grudl.com $
 * @param Paginator $paginator
 * @param array     $steps
 *}

{if $paginator->pageCount > 1}
<div class="paginator">
	{if $paginator->isFirst()}
	<span class="paginator-button">«</span>
	{else}
	<a href="{link this, 'page' => $paginator->page - 1}">«</a>
	{/if}

	{foreach $steps as $step}
	{if $step == $paginator->page}
		<span class="paginator-current">{$step}</span>
	{else}
		<a href="{link this, 'page' => $step}">{$step}</a>
	{/if}
	{if $iterator->nextValue > $step + 1}<span>…</span>{/if}
	{/foreach}

	{if $paginator->isLast()}
	<span class="paginator-button">»</span>
	{else}
	<a href="{link this, 'page' => $paginator->page + 1}">»</a>
	{/if}
	<script src="{$basePath}/js/jquery.js"></script>
	<script type="text/javascript">
$().keydown(function (event) {
    if (event.keyCode == 37) {
        // go left
        $('.paginator-current').prev().click();
    } else if (event.keyCode == 39) {
        // go right
        $('.paginator-current').next().click();
    }
});
	</script>
</div>
{/if}
