<?php

/**
 * Default error page.
 * @param  string $error
 */

namespace Tracy;

?>
<!DOCTYPE html><!-- "' --></script></style></noscript></xmp>
<meta charset="utf-8">
<meta name=robots content=noindex>
<meta name=generator content="Tracy">
<title>Server Error</title>

<div id="tracy-error-body">
<style>body{color:#333;background:white;width:500px;margin:100px auto}h1{font:bold 47px/1.5 sans-serif;margin:.6em 0}p{font:21px/1.5 Georgia,serif;margin:1.5em 0}small{font-size:70%;color:gray}</style>

<h1>Chyba</h1>

<p>Omlouváme se, ale na stránkách došlo k neočekávané chybě.
Můžeme vás ujistit, že tým cvičených opic usilovně pracuje na
vyřešení tohoto probému. Zkuste se tu znovu zastavit později.</p>

<p><small>error 500<?php if (!empty($error)) echo "<br>Tracy says: ", htmlspecialchars($error) ?></small></p>
<div>

<script>/*<![CDATA[*/document.documentElement.innerHTML="<title>Server Error</title>"+document.getElementById("tracy-error-body").innerHTML;/*]]>*/</script>
